# What values are returned during the following sequence of deque ADT operations, on initially empty deque.

# add_first(4)      -       [4]
# add_last(8)       -       [4,8]
# add_last(9)       -       [4,8,9]
# add_first(5)      -       [5,4,8,9]
# back() (last()?)  9       [5,6,8,9]
# delete_first()    5       [6,8,9]
# delete_last()     9       [6,8]
# add_last(7)       -       [6,8,7]
# first()           6       [6,8,7]
# last()            7       [6,8,7]
# add_last(6)       -       [6,8,7,6]
# delete_first()    -       [8,7,6]
# delete_first()    -       [7,6]        
